//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/nl.vinyamar.jks.jaxb">http://java.sun.com/xml/nl.vinyamar.jks.jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 08:55:10 AM CET 
//


package nl.vinyamar.jks.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for Agreement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Agreement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AgreementType" type="{http://www.ing.com/lchs}agreementType"/>
 *         &lt;element name="ExternalAgreementId" type="{http://www.ing.com/lchs}externalAgreementId"/>
 *         &lt;element name="PartyAgreementRole" type="{http://www.ing.com/lchc}PartyAgreementRole"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Agreement", propOrder = {
    "agreementType",
    "externalAgreementId",
    "partyAgreementRole"
})
public class Agreement {

    @XmlElement(name = "AgreementType", required = true)
    protected String agreementType;
    @XmlElement(name = "ExternalAgreementId", required = true)
    protected String externalAgreementId;
    @XmlElement(name = "PartyAgreementRole", required = true)
    protected PartyAgreementRole partyAgreementRole;

    /**
     * Gets the value of the agreementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementType() {
        return agreementType;
    }

    /**
     * Sets the value of the agreementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementType(String value) {
        this.agreementType = value;
    }

    /**
     * Gets the value of the externalAgreementId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalAgreementId() {
        return externalAgreementId;
    }

    /**
     * Sets the value of the externalAgreementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalAgreementId(String value) {
        this.externalAgreementId = value;
    }

    /**
     * Gets the value of the partyAgreementRole property.
     * 
     * @return
     *     possible object is
     *     {@link PartyAgreementRole }
     *     
     */
    public PartyAgreementRole getPartyAgreementRole() {
        return partyAgreementRole;
    }

    /**
     * Sets the value of the partyAgreementRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyAgreementRole }
     *     
     */
    public void setPartyAgreementRole(PartyAgreementRole value) {
        this.partyAgreementRole = value;
    }

}
