//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/nl.vinyamar.jks.jaxb">http://java.sun.com/xml/nl.vinyamar.jks.jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 08:55:10 AM CET 
//


package nl.vinyamar.jks.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;

/**
 * <p>Java class for Agreement2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Agreement2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AgreementName" type="{http://www.ing.com/lchs}agreementName"/>
 *         &lt;element name="AgreementType" type="{http://www.ing.com/lchs}agreementType"/>
 *         &lt;element name="ExternalAgreementId" type="{http://www.ing.com/lchs}externalAgreementId"/>
 *         &lt;element name="Status" type="{http://www.ing.com/lchs}AgrmntStatus"/>
 *         &lt;element name="StartDate" type="{http://www.ing.com/lchgs}date"/>
 *         &lt;element name="EndDate" type="{http://www.ing.com/lchgs}date"/>
 *         &lt;element name="PointsBalance" type="{http://www.ing.com/lchs}pointsBalance" minOccurs="0"/>
 *         &lt;element name="PartyAgreementRole" type="{http://www.ing.com/lchc}PartyAgreementRole"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Agreement2", propOrder = {
    "agreementName",
    "agreementType",
    "externalAgreementId",
    "status",
    "startDate",
    "endDate",
    "pointsBalance",
    "partyAgreementRole"
})
public class Agreement2 {

    @XmlElement(name = "AgreementName", required = true)
    protected String agreementName;
    @XmlElement(name = "AgreementType", required = true)
    protected String agreementType;
    @XmlElement(name = "ExternalAgreementId", required = true)
    protected String externalAgreementId;
    @XmlElement(name = "Status", required = true)
    protected AgrmntStatus status;
    @XmlElement(name = "StartDate", required = true)
    protected BigInteger startDate;
    @XmlElement(name = "EndDate", required = true)
    protected BigInteger endDate;
    @XmlElement(name = "PointsBalance")
    protected BigInteger pointsBalance;
    @XmlElement(name = "PartyAgreementRole", required = true)
    protected PartyAgreementRole partyAgreementRole;

    /**
     * Gets the value of the agreementName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementName() {
        return agreementName;
    }

    /**
     * Sets the value of the agreementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementName(String value) {
        this.agreementName = value;
    }

    /**
     * Gets the value of the agreementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgreementType() {
        return agreementType;
    }

    /**
     * Sets the value of the agreementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgreementType(String value) {
        this.agreementType = value;
    }

    /**
     * Gets the value of the externalAgreementId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalAgreementId() {
        return externalAgreementId;
    }

    /**
     * Sets the value of the externalAgreementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalAgreementId(String value) {
        this.externalAgreementId = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link AgrmntStatus }
     *     
     */
    public AgrmntStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgrmntStatus }
     *     
     */
    public void setStatus(AgrmntStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setStartDate(BigInteger value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setEndDate(BigInteger value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the pointsBalance property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPointsBalance() {
        return pointsBalance;
    }

    /**
     * Sets the value of the pointsBalance property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setPointsBalance(BigInteger value) {
        this.pointsBalance = value;
    }

    /**
     * Gets the value of the partyAgreementRole property.
     * 
     * @return
     *     possible object is
     *     {@link PartyAgreementRole }
     *     
     */
    public PartyAgreementRole getPartyAgreementRole() {
        return partyAgreementRole;
    }

    /**
     * Sets the value of the partyAgreementRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyAgreementRole }
     *     
     */
    public void setPartyAgreementRole(PartyAgreementRole value) {
        this.partyAgreementRole = value;
    }

}
