//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/nl.vinyamar.jks.jaxb">http://java.sun.com/xml/nl.vinyamar.jks.jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 08:55:10 AM CET 
//


package nl.vinyamar.jks.jaxb;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AuditTrailInfo" type="{http://www.ing.com/lchgs}auditTrailInformation"/>
 *         &lt;element name="Party" type="{http://www.ing.com/lchc}Party" maxOccurs="2"/>
 *         &lt;element name="AgreementFrom" type="{http://www.ing.com/lchc}Agreement" maxOccurs="2" minOccurs="2"/>
 *         &lt;element name="AgreementTo" type="{http://www.ing.com/lchc}Agreement"/>
 *         &lt;element name="Payment" type="{http://www.ing.com/lchc}Payment"/>
 *         &lt;element name="Security" type="{http://www.ing.com/lchc}Security"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "auditTrailInfo",
    "party",
    "agreementFrom",
    "agreementTo",
    "payment",
    "security"
})
@XmlRootElement(name = "AuthorizeLoyaltyPaymentREQ", namespace = "http://www.ing.com/lch/alp")
public class AuthorizeLoyaltyPaymentREQ {

    @XmlElement(name = "AuditTrailInfo", required = true)
    protected String auditTrailInfo;
    @XmlElement(name = "Party", required = true)
    protected List<Party> party;
    @XmlElement(name = "AgreementFrom", required = true)
    protected List<Agreement> agreementFrom;
    @XmlElement(name = "AgreementTo", required = true)
    protected Agreement agreementTo;
    @XmlElement(name = "Payment", required = true)
    protected Payment payment;
    @XmlElement(name = "Security", required = true)
    protected Security security;

    /**
     * Gets the value of the auditTrailInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditTrailInfo() {
        return auditTrailInfo;
    }

    /**
     * Sets the value of the auditTrailInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditTrailInfo(String value) {
        this.auditTrailInfo = value;
    }

    /**
     * Gets the value of the party property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the party property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Party }
     * 
     * 
     */
    public List<Party> getParty() {
        if (party == null) {
            party = new ArrayList<Party>();
        }
        return this.party;
    }

    /**
     * Gets the value of the agreementFrom property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the agreementFrom property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAgreementFrom().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Agreement }
     * 
     * 
     */
    public List<Agreement> getAgreementFrom() {
        if (agreementFrom == null) {
            agreementFrom = new ArrayList<Agreement>();
        }
        return this.agreementFrom;
    }

    /**
     * Gets the value of the agreementTo property.
     * 
     * @return
     *     possible object is
     *     {@link Agreement }
     *     
     */
    public Agreement getAgreementTo() {
        return agreementTo;
    }

    /**
     * Sets the value of the agreementTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agreement }
     *     
     */
    public void setAgreementTo(Agreement value) {
        this.agreementTo = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link Payment }
     *     
     */
    public Payment getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payment }
     *     
     */
    public void setPayment(Payment value) {
        this.payment = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link Security }
     *     
     */
    public Security getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setSecurity(Security value) {
        this.security = value;
    }

}
