//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/nl.vinyamar.jks.jaxb">http://java.sun.com/xml/nl.vinyamar.jks.jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 08:55:10 AM CET 
//


package nl.vinyamar.jks.jaxb;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AuditTrailInfo" type="{http://www.ing.com/lchgs}auditTrailInformation"/>
 *         &lt;element name="AsIsDate" type="{http://www.ing.com/lchgs}date"/>
 *         &lt;element name="Party" type="{http://www.ing.com/lchc}Party3"/>
 *         &lt;element name="Agreement" type="{http://www.ing.com/lchc}Agreement3"/>
 *         &lt;element name="Security" type="{http://www.ing.com/lchc}Security"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "auditTrailInfo",
    "asIsDate",
    "party",
    "agreement",
    "security"
})
@XmlRootElement(name = "GetDeliveryAddressREQ", namespace = "http://www.ing.com/lch/gda")
public class GetDeliveryAddressREQ {

    @XmlElement(name = "AuditTrailInfo", required = true)
    protected String auditTrailInfo;
    @XmlElement(name = "AsIsDate", required = true)
    protected BigInteger asIsDate;
    @XmlElement(name = "Party", required = true)
    protected Party3 party;
    @XmlElement(name = "Agreement", required = true)
    protected Agreement3 agreement;
    @XmlElement(name = "Security", required = true)
    protected Security security;

    /**
     * Gets the value of the auditTrailInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditTrailInfo() {
        return auditTrailInfo;
    }

    /**
     * Sets the value of the auditTrailInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditTrailInfo(String value) {
        this.auditTrailInfo = value;
    }

    /**
     * Gets the value of the asIsDate property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getAsIsDate() {
        return asIsDate;
    }

    /**
     * Sets the value of the asIsDate property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setAsIsDate(BigInteger value) {
        this.asIsDate = value;
    }

    /**
     * Gets the value of the party property.
     * 
     * @return
     *     possible object is
     *     {@link Party3 }
     *     
     */
    public Party3 getParty() {
        return party;
    }

    /**
     * Sets the value of the party property.
     * 
     * @param value
     *     allowed object is
     *     {@link Party3 }
     *     
     */
    public void setParty(Party3 value) {
        this.party = value;
    }

    /**
     * Gets the value of the agreement property.
     * 
     * @return
     *     possible object is
     *     {@link Agreement3 }
     *     
     */
    public Agreement3 getAgreement() {
        return agreement;
    }

    /**
     * Sets the value of the agreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Agreement3 }
     *     
     */
    public void setAgreement(Agreement3 value) {
        this.agreement = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link Security }
     *     
     */
    public Security getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link Security }
     *     
     */
    public void setSecurity(Security value) {
        this.security = value;
    }

}
