//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/nl.vinyamar.jks.jaxb">http://java.sun.com/xml/nl.vinyamar.jks.jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 08:55:10 AM CET 
//


package nl.vinyamar.jks.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the nl.ing.ws.lar.nl.vinyamar.jks.jaxb package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.ing.ws.lar.nl.vinyamar.jks.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthorizeLoyaltyCorrectionPaymentRLY }
     * 
     */
    public AuthorizeLoyaltyCorrectionPaymentRLY createAuthorizeLoyaltyCorrectionPaymentRLY() {
        return new AuthorizeLoyaltyCorrectionPaymentRLY();
    }

    /**
     * Create an instance of {@link Security }
     * 
     */
    public Security createSecurity() {
        return new Security();
    }

    /**
     * Create an instance of {@link AuthorizeLoyaltyCorrectionPaymentREQ }
     * 
     */
    public AuthorizeLoyaltyCorrectionPaymentREQ createAuthorizeLoyaltyCorrectionPaymentREQ() {
        return new AuthorizeLoyaltyCorrectionPaymentREQ();
    }

    /**
     * Create an instance of {@link Party }
     * 
     */
    public Party createParty() {
        return new Party();
    }

    /**
     * Create an instance of {@link Agreement }
     * 
     */
    public Agreement createAgreement() {
        return new Agreement();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link PartyAgreementRole }
     * 
     */
    public PartyAgreementRole createPartyAgreementRole() {
        return new PartyAgreementRole();
    }

    /**
     * Create an instance of {@link PersonDemographics }
     * 
     */
    public PersonDemographics createPersonDemographics() {
        return new PersonDemographics();
    }

    /**
     * Create an instance of {@link Person2 }
     * 
     */
    public Person2 createPerson2() {
        return new Person2();
    }

    /**
     * Create an instance of {@link AccountInfo }
     * 
     */
    public AccountInfo createAccountInfo() {
        return new AccountInfo();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link PostalAddress }
     * 
     */
    public PostalAddress createPostalAddress() {
        return new PostalAddress();
    }

    /**
     * Create an instance of {@link Agreement4 }
     * 
     */
    public Agreement4 createAgreement4() {
        return new Agreement4();
    }

    /**
     * Create an instance of {@link Agreement3 }
     * 
     */
    public Agreement3 createAgreement3() {
        return new Agreement3();
    }

    /**
     * Create an instance of {@link Agreement2 }
     * 
     */
    public Agreement2 createAgreement2() {
        return new Agreement2();
    }

    /**
     * Create an instance of {@link Caller }
     * 
     */
    public Caller createCaller() {
        return new Caller();
    }

    /**
     * Create an instance of {@link Party2 }
     * 
     */
    public Party2 createParty2() {
        return new Party2();
    }

    /**
     * Create an instance of {@link Party3 }
     * 
     */
    public Party3 createParty3() {
        return new Party3();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Selection }
     * 
     */
    public Selection createSelection() {
        return new Selection();
    }

    /**
     * Create an instance of {@link AuthorizeLoyaltyPaymentRLY }
     * 
     */
    public AuthorizeLoyaltyPaymentRLY createAuthorizeLoyaltyPaymentRLY() {
        return new AuthorizeLoyaltyPaymentRLY();
    }

    /**
     * Create an instance of {@link AuthorizeLoyaltyPaymentREQ }
     * 
     */
    public AuthorizeLoyaltyPaymentREQ createAuthorizeLoyaltyPaymentREQ() {
        return new AuthorizeLoyaltyPaymentREQ();
    }

    /**
     * Create an instance of {@link GetDeliveryAddressRLY }
     * 
     */
    public GetDeliveryAddressRLY createGetDeliveryAddressRLY() {
        return new GetDeliveryAddressRLY();
    }

    /**
     * Create an instance of {@link GetDeliveryAddressREQ }
     * 
     */
    public GetDeliveryAddressREQ createGetDeliveryAddressREQ() {
        return new GetDeliveryAddressREQ();
    }

    /**
     * Create an instance of {@link AuthorizeAccessAndLoyaltyCustomerREQ }
     * 
     */
    public AuthorizeAccessAndLoyaltyCustomerREQ createAuthorizeAccessAndLoyaltyCustomerREQ() {
        return new AuthorizeAccessAndLoyaltyCustomerREQ();
    }

    /**
     * Create an instance of {@link AuthorizeAccessAndLoyaltyCustomerRLY }
     * 
     */
    public AuthorizeAccessAndLoyaltyCustomerRLY createAuthorizeAccessAndLoyaltyCustomerRLY() {
        return new AuthorizeAccessAndLoyaltyCustomerRLY();
    }

    /**
     * Create an instance of {@link InquireLoyaltyContextDataRLY }
     * 
     */
    public InquireLoyaltyContextDataRLY createInquireLoyaltyContextDataRLY() {
        return new InquireLoyaltyContextDataRLY();
    }

    /**
     * Create an instance of {@link InquireLoyaltyContextDataREQ }
     * 
     */
    public InquireLoyaltyContextDataREQ createInquireLoyaltyContextDataREQ() {
        return new InquireLoyaltyContextDataREQ();
    }

}
