//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/nl.vinyamar.jks.jaxb">http://java.sun.com/xml/nl.vinyamar.jks.jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 08:55:10 AM CET 
//


package nl.vinyamar.jks.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;

/**
 * <p>Java class for Payment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Payment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Amount" type="{http://www.ing.com/lchs}amount"/>
 *         &lt;element name="Currency" type="{http://www.ing.com/lchs}currency"/>
 *         &lt;element name="CommentLine1" type="{http://www.ing.com/lchs}commentLine" minOccurs="0"/>
 *         &lt;element name="CommentLine2" type="{http://www.ing.com/lchs}commentLine" minOccurs="0"/>
 *         &lt;element name="CommentLine3" type="{http://www.ing.com/lchs}commentLine" minOccurs="0"/>
 *         &lt;element name="CommentLine4" type="{http://www.ing.com/lchs}commentLine" minOccurs="0"/>
 *         &lt;element name="Points" type="{http://www.ing.com/lchs}points"/>
 *         &lt;element name="OrderId" type="{http://www.ing.com/lchs}orderId"/>
 *         &lt;element name="Description1" type="{http://www.ing.com/lchs}description" minOccurs="0"/>
 *         &lt;element name="Description2" type="{http://www.ing.com/lchs}description" minOccurs="0"/>
 *         &lt;element name="Description3" type="{http://www.ing.com/lchs}description" minOccurs="0"/>
 *         &lt;element name="Description4" type="{http://www.ing.com/lchs}description" minOccurs="0"/>
 *         &lt;element name="Description5" type="{http://www.ing.com/lchs}description" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Payment", propOrder = {
    "amount",
    "currency",
    "commentLine1",
    "commentLine2",
    "commentLine3",
    "commentLine4",
    "points",
    "orderId",
    "description1",
    "description2",
    "description3",
    "description4",
    "description5"
})
public class Payment {

    @XmlElement(name = "Amount", required = true)
    protected BigInteger amount;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "CommentLine1")
    protected String commentLine1;
    @XmlElement(name = "CommentLine2")
    protected String commentLine2;
    @XmlElement(name = "CommentLine3")
    protected String commentLine3;
    @XmlElement(name = "CommentLine4")
    protected String commentLine4;
    @XmlElement(name = "Points", required = true)
    protected BigInteger points;
    @XmlElement(name = "OrderId", required = true)
    protected String orderId;
    @XmlElement(name = "Description1")
    protected String description1;
    @XmlElement(name = "Description2")
    protected String description2;
    @XmlElement(name = "Description3")
    protected String description3;
    @XmlElement(name = "Description4")
    protected String description4;
    @XmlElement(name = "Description5")
    protected String description5;

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *
     */
    public void setAmount(BigInteger value) {
        this.amount = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the commentLine1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCommentLine1() {
        return commentLine1;
    }

    /**
     * Sets the value of the commentLine1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCommentLine1(String value) {
        this.commentLine1 = value;
    }

    /**
     * Gets the value of the commentLine2 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCommentLine2() {
        return commentLine2;
    }

    /**
     * Sets the value of the commentLine2 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCommentLine2(String value) {
        this.commentLine2 = value;
    }

    /**
     * Gets the value of the commentLine3 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCommentLine3() {
        return commentLine3;
    }

    /**
     * Sets the value of the commentLine3 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCommentLine3(String value) {
        this.commentLine3 = value;
    }

    /**
     * Gets the value of the commentLine4 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCommentLine4() {
        return commentLine4;
    }

    /**
     * Sets the value of the commentLine4 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCommentLine4(String value) {
        this.commentLine4 = value;
    }

    /**
     * Gets the value of the points property.
     *
     * @return
     *     possible object is
     *     {@link java.math.BigInteger }
     *
     */
    public BigInteger getPoints() {
        return points;
    }

    /**
     * Sets the value of the points property.
     *
     * @param value
     *     allowed object is
     *     {@link java.math.BigInteger }
     *     
     */
    public void setPoints(BigInteger value) {
        this.points = value;
    }

    /**
     * Gets the value of the orderId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * Sets the value of the orderId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderId(String value) {
        this.orderId = value;
    }

    /**
     * Gets the value of the description1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription1() {
        return description1;
    }

    /**
     * Sets the value of the description1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription1(String value) {
        this.description1 = value;
    }

    /**
     * Gets the value of the description2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription2() {
        return description2;
    }

    /**
     * Sets the value of the description2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription2(String value) {
        this.description2 = value;
    }

    /**
     * Gets the value of the description3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription3() {
        return description3;
    }

    /**
     * Sets the value of the description3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription3(String value) {
        this.description3 = value;
    }

    /**
     * Gets the value of the description4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription4() {
        return description4;
    }

    /**
     * Sets the value of the description4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription4(String value) {
        this.description4 = value;
    }

    /**
     * Gets the value of the description5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription5() {
        return description5;
    }

    /**
     * Sets the value of the description5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription5(String value) {
        this.description5 = value;
    }

}
