//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/nl.vinyamar.jks.jaxb">http://java.sun.com/xml/nl.vinyamar.jks.jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.12 at 08:55:10 AM CET 
//


package nl.vinyamar.jks.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for PersonName complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonName">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PreTitles" type="{http://www.ing.com/lchs}preTitles" minOccurs="0"/>
 *         &lt;element name="NameSuffix" type="{http://www.ing.com/lchs}nameSuffix" minOccurs="0"/>
 *         &lt;element name="Initials" type="{http://www.ing.com/lchs}initials" minOccurs="0"/>
 *         &lt;element name="FirstNames" type="{http://www.ing.com/lchs}firstNames" minOccurs="0"/>
 *         &lt;element name="LastName" type="{http://www.ing.com/lchs}lastName" minOccurs="0"/>
 *         &lt;element name="LastNamePrefix" type="{http://www.ing.com/lchs}lastNamePrefix" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonName", propOrder = {
    "preTitles",
    "nameSuffix",
    "initials",
    "firstNames",
    "lastName",
    "lastNamePrefix"
})
public class PersonName {

    @XmlElement(name = "PreTitles")
    protected String preTitles;
    @XmlElement(name = "NameSuffix")
    protected String nameSuffix;
    @XmlElement(name = "Initials")
    protected String initials;
    @XmlElement(name = "FirstNames")
    protected String firstNames;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "LastNamePrefix")
    protected String lastNamePrefix;

    /**
     * Gets the value of the preTitles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreTitles() {
        return preTitles;
    }

    /**
     * Sets the value of the preTitles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreTitles(String value) {
        this.preTitles = value;
    }

    /**
     * Gets the value of the nameSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSuffix() {
        return nameSuffix;
    }

    /**
     * Sets the value of the nameSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSuffix(String value) {
        this.nameSuffix = value;
    }

    /**
     * Gets the value of the initials property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInitials() {
        return initials;
    }

    /**
     * Sets the value of the initials property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInitials(String value) {
        this.initials = value;
    }

    /**
     * Gets the value of the firstNames property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstNames() {
        return firstNames;
    }

    /**
     * Sets the value of the firstNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstNames(String value) {
        this.firstNames = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the lastNamePrefix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastNamePrefix() {
        return lastNamePrefix;
    }

    /**
     * Sets the value of the lastNamePrefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastNamePrefix(String value) {
        this.lastNamePrefix = value;
    }

}
